### ISSUE TITLE
Extract repository methods to traits

### ISSUE THREAD

**Issue by loevgaard** [Sylius/AdminOrderCreationPlugin#140]
If you extract the concrete methods in the repositories to traits it would be easier to use the plugin, i.e. you could just `use` the trait and implement the interface and you would be good to go. Now you have to copy the method manually.

**Comment by nediam** [comment]
...and it would solve problem with having the same overwritten repository class in another plugin, now when you have 2 plugins that has their own methods for example in `CustomerRepository` you cant use both plugins. In AdminOrderCreationPlugin case it's easy to hack it with not importing its config (`@SyliusAdminOrderCreationPlugin/Resources/config/app/config.yml`) but writing it by hand and putting the same methods in application custom repo because it used only in `Resources/config/app/ajax.yml` without any injection. But it would be good practice for all plugins not only this one. wdyt?

**Comment by igormukhingmailcom** [comment]
I will make PR now

**Comment by igormukhingmailcom** [comment]
@Zales0123, I would say this is bug. As it break things once any other plugin that extends `CustomerRepository` or `ProductVariantRepository` come into place.
