### ISSUE TITLE
Customer Reorder Integration

### ISSUE THREAD

**Issue by mamazu** [Sylius/AdminOrderCreationPlugin#47]
Steps to reproduce:
- Create a customer
- Create an order with discounts on the order or the order items
- Try to reorder this order and the order does not have the discount applied.

I don't know if that is expected behavior.

**Comment by CoderMaggie** [comment]
Hi Max @mamazu :) 

In my opinion this is expected behaviour, as the discounts the admin is giving are very custom, and probably relevant in the moment of giving those discounts. That is why we clear them.

The only discounts that will be applied are the promotions that are automatically applied in the shop (for instance: 10% on order total when the order total is >100$).

Is it okay for you? If you wish to have any other behaviour, please give me a scenario. Then we will be able to help you with customization or propose a solution in plugin.

**Comment by mamazu** [comment]
Ah, okay so you thought of it. It makes sense to me too. So I guess question closed.
